server:
  proxied: true
  assets-path: /app/assets

branding:
  hide-footer: true
  custom-footer: |
    <p>無字倉頡のホームページ Powered by <a href="https://github.com/glanceapp/glance">Glance</a></p>
  logo-url: /assets/logo.webp
  favicon-url: /assets/favicon.png
  app-name: "WUZI Dashboard"
  app-icon-url: /assets/app-icon.png
  app-background-color: "#2e2e2e"

theme:
  # background-color: 240 8 9
  # primary-color: 43 50 70
  # positive-color: 43 50 70
  # negative-color: 0 70 70
  # contrast-multiplier: 1
  # text-saturation-multiplier: 1
  disable-picker: true

pages:
  - $include: home.yml
  - $include: market.yml
  - $include: homelab.yml

auth:
  secret-key: ${GLANCE_SECRET_KEY}
  users:
    admin:
      password: ${GLANCE_ADMIN_PASSWORD}
    wuzi:
      password: ${GLANCE_WUZI_PASSWORD}
    guest:
      password: ${GLANCE_GUEST_PASSWORD}