- name: Homelab
  desktop-navigation-width: wide
  show-mobile-header: true
  width: wide

  columns:
    - size: small
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: My Home Server
              hide-swap: true
              hide-mountpoints-by-default: true
              mountpoints:
                "/mnt/root/":
                  name: Root
                  hide: false

        - type: bookmarks
          groups:
            - title: Server Management
              hide-arrow: true
              links:
                - title: Synology DSM
                  url: https://wuzicangjie.quickconnect.to/
                - title: UNRAID CONNECT
                  url: https://connect.myunraid.net/
                - title: Linode Cloud Manager
                  url: https://cloud.linode.com/
                - title: Tailscale Admin Console
                  url: https://login.tailscale.com/admin/machines
                - title: Cloudflare One
                  url: https://one.dash.cloudflare.com/
            - title: Local Access
              hide-arrow: true
              links:
                - title: Archer BE9300
                  url: http://192.168.0.3/
                - title: Aterm
                  url: http://192.168.0.1/
                - title: UNRAID WebUI
                  url: http://192.168.0.21/      







