- name: RSS
  desktop-navigation-width: wide
  show-mobile-header: false
  width: wide

  columns:
    - size: full
      widgets:
        - type: iframe
          hide-header: true
          source: https://freshrss.wuzicangjie.com/
          # height: 1080